name: MQ3 Labs
favicon: null
layout_spectrum: 0.49572
typography_spectrum: 0
title: MQ3 Labs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4dd8ff'
    - '#ffffff'
    - '#01ffff'
    - '#bfffff'
    - '#9ae9fe'
  brandStrength: 0.1875
  lightness: 0.6143948212265968
  saturation: 0.5866543708834797
  rhythmicContrast: 0.833139099413529
purpose: []
