name: MQ3 Labs
favicon: null
layout_spectrum: 0.43335274886339903
typography_spectrum: 0.8090164947789162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08266187668778002
  lightness: 0.6143948212265968
  saturation: 0.5866543708834797
  rhythmicContrast: 0.833139099413529
purpose: []
